[package]
name = "notebk"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]

[dependencies]
ansi_term = "0.11.0"
dirs = "1.0"
time = { version = "0.3", features = ["macros", "formatting", "local-offset", "parsing"]}
